<?php 

$data = [
	[
		'name' => 'Gambero e tartufo',
		'description' => 'gambero e tartufo, 8 pezzi.',
		'price' => '13.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Involtini di primavera',
		'description' => 'Carote, cipolla e cavoli, 2 pezzi',
		'price' => '2.00',
		'img' => '',
		'veg' => 1,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Patatine',
		'description' => 'Patatine fritte',
		'price' => '3.00',
		'img' => '',
		'veg' => 1,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli alla griglia',
		'description' => 'Farina, carne di maiale, 4 pezzi',
		'price' => '3.50',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli di carne al vapore',
		'description' => 'Farina e carne di maiale, 4 pezzi',
		'price' => '3.50',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli di gamberi giapponesi',
		'description' => 'Farina di frumento, zenzero e gamberi, 4 pezzi',
		'price' => '4.00',
		'img' => '',
		'veg' => 0,
		'availability' => 0,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Sashimi sake',
		'description' => 'Filetti di salmone, 13 pezzi',
		'price' => '12.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Sashimi tuna',
		'description' => 'Filetti di tonno, 13 pezzi',
		'price' => '13.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri sake',
		'description' => 'Riso, salmone, 2 pezzi',
		'price' => '2.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri suzuki',
		'description' => 'Riso, branzino, 2 pezzi',
		'price' => '2.50',
		'img' => '',
		'veg' => 0,
		'availability' => 0,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri maguro',
		'description' => 'Riso, tonno, 2 pezzi',
		'price' => '3.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri ebiten',
		'description' => 'Riso, gambero fritto, 2 pezzi',
		'price' => '4.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Uramaki ebiten',
		'description' => 'tempura di gamberi, salsa teriyaki, pasta kataifi e sesamo',
		'price' => '8.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
	[
		'name' => 'Uramaki Tiger Roll',
		'description' => 'tempura di gamberi, salsa teriyaki, rivestito con salmone',
		'price' => '12.00',
		'img' => '',
		'veg' => 0,
		'availability' => 1,
		'restaurant_id' => '6',
	],
    [
        'name' => 'Piadina Falafel Veggie',
        'description' => 'Piadina con polpette di ceci e spezie, insalata, patatine e salsa a scelta',
        'price' => '4.50',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '10',
    ],
    [
        'name' => 'Beef Burger',
        'description' => 'Panino con burger di manzo, formaggio, cetrioli, pomodoro e insalata',
        'price' => '3.70',
        'img' => '',
        'veg' => 0,
        'availability' => 0,
        'restaurant_id' => '10'
    ],
    [
        'name' => 'Indiano',
        'description' => '1 samosa, 1 cingara, 1 involtino primavera',
        'price' => '5.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10'
    ],
    [
        'name' => 'Riso Biryani',
        'description' => 'Riso biryani con carne di vitello',
        'price' => '6.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10'
    ],
    [
        'name' => 'Kebab al Curry',
        'description' => 'Salsa al curry, pomodoro, lattuga e kebab',
        'price' => '5.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10'
    ],
    [
        'name' => 'Kebab al pepe verde',
        'description' => 'Salsa al pepe verde, cipolla, pomodoro, lattuga e kebab',
        'price' => '4.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10',
    ],
    [
        'name' => 'Kebab Mediterraneo',
        'description' => 'Salsa mediterranea, lattuga, pomodoro, cipolla e kebab',
        'price' => '6.20',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10',
    ],
    [
        'name' => 'Piatto Hallal',
        'description' => 'Salsa al curry, salsa allo yogurt, pomodoro, lattuga, cipolla, peperoni, radicchio, kebab, patatine',
        'price' => '7.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
        'restaurant_id' => '10',
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Bacon King 3.0 BBQ',
        'description' => "Da veri king! Una nuova ed irresistibile versione del Bacon King 3.0 con l'esclusiva salsa BBQ, solo per veri king!",
        'price' => '8.90',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/p2wyj3ljkqlxehoqvi9n',
        'veg' => 0,
        'availability' => 1,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Chicken bacon king',
        'description' => "Bacon e pollo! Petto di pollo croccante in un morbido panino al mais, 8 fette di bacon, formaggio cheddar, ketchup, maionese",
        'price' => '7.20',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/nhqlskc4kxx3dadv7tzr',
        'veg' => 0,
        'availability' => 1,
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Double Cheese Bacon',
        'description' => "Semplice goloso. Doppio hamburger, formaggio cheddar e bacon. Cosa puoi chiedere di più?",
        'price' => '4.90',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/vimsljafaybzumdaxcm0',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Big King Menu',
        'description' => "Non mi basta.Il nostro Big King con doppia carne di manzo alla griglia, doppio formaggio e deliziosa salsa King",
        'price' => '8.20',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/i61tvetcyhy1g6e9pnvw',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Crispy chicken Menu',
        'description' => "Semplicità color oro. Filetto di pollo in croccante panatura speziata. Pomodoro, lattuga e maionese.",
        'price' => '7.20',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/tpf7mt3kjfkukdwtklot',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'King Nuggets - 20 pezzi',
        'description' => "Tenere pepite di pollo croccante.",
        'price' => '11.20',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/tvsnju6rbeyuaa4pn56i',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Chili Cheese Bites - 9 pezzi',
        'description' => "Pepite panate di formaggio fuso ripiene di jalapenos.",
        'price' => '4.70',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/lvoyfuimxu5myulornik',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Fries Formato Large Delivery',
        'description' => "Dorate e croccanti patatine fritte.",
        'price' => '2.90',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/ryyzislbjfigshvhthwu',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'King Fusion Oreo',
        'description' => "Soffice gelato alla vaniglia con biscotti Oreo.",
        'price' => '2.90',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/vwyev9jnjixxwpurc2cr',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Ben & Jerry Cookie Dough 100 ml',
        'description' => "Gelato alla vaniglia, pezzi di biscotto al cioccolato e pezzi di copertura al cacao.",
        'price' => '3.70',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/zyrwzdavi2sxljzfmaw1',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Acqua naturale',
        'description' => "50 cl.",
        'price' => '1.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/gmzjkcaaosmidrmuqloo',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Coca-Cola 45 cl',
        'description' => "45 cl.",
        'price' => '2.90',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/q1vh3dsnyugxdj5w94xk',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Ichnusa-33cl',
        'description' => "Lattina.",
        'price' => '4.50',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/gwhxl61sz7vd0hqxglzt',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Maionese',
        'description' => "",
        'price' => '0.35',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/ttzkmmd4yl5d9n9pxtyo',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Ketchup',
        'description' => "",
        'price' => '0.35',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/sftpl47rz4twiveepki0',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'name' => 'Vaschetta triplo cioccolato 500gr',
        'description' => 'Cioccolato bianco, Cioccolato al latte, 	Cioccolato fondente',
        'price' => '15.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    [
        'name' => 'Vaschetta triplo cioccolato 1kg',
        'description' => 'Cioccolato bianco, Cioccolato al latte, 	Cioccolato fondente',
        'price' => '25.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    
    ],
    
    [
        'name' => 'Vaschetta frutta 500gr',
        'description' => 'Amarena, Fragola, Ananas, Albicocca, 	Melone, Banana',
        'price' => '15.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta frutta 1kg',
        'description' => 'Amarena, Fragola, Ananas, Albicocca, 	Melone, Banana',
        'price' => '25.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta tropical 500gr',
        'description' => 'Ananas, Mango, Maracuja',
        'price' => '15.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta tropical 1kg',
        'description' => 'Ananas, Mango, Maracuja',
        'price' => '25.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta dolce 500gr',
        'description' => 'Kinder pinguino, Kinder cereali, 	Nutella, Nocciola',
        'price' => '15.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta dolce 1kg',
        'description' => 'Kinder pinguino, Kinder cereali, 	Nutella, Nocciola',
        'price' => '25.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    
    [
        'name' => 'Vaschetta personalizzata 500gr',
        'description' => 'Scegli i tuoi gusti preferiti, fino ad un massimo di 6',
        'price' => '15.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    [
        'name' => 'Vaschetta personalizzata 1kg',
        'description' => 'Scegli i tuoi gusti preferiti, fino ad un massimo di 6',
        'price' => '25.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
        'restaurant_id' => '11',
    ],
    [
        'name' => 'Cheesecake - Trancio',
        'description' => 'Forse la torta più famosa del mondo, nella originale verione newyorkese, ovvero al forno con fondo di biscotto digestive, cremoso al formaggio e copertura a scelta',
        'price' => '5.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Chocosette',
        'description' => 'La nostra versione della setteveli. Biscotto al cioccolato, bavarese alla nocciola, mousse al cioccolato fondente, croccante di nocciole e glassa al cioccolato, bavarese alla nocciola, mousse al cioccolato fondente, croccante di nocciole e glassa al cioccolato',
        'price' => '5.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Chocostar',
        'description' => 'Versione al pistacchio della setteveli: Biscotto al cioccolato, bavarese al pistacchio, mousse al cioccolato fondente, croccante di pistacchio e glassa al cioccolato',
        'price' => '5.50',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Lindor Cake',
        'description' => 'Torta dedicata al cioccolatino più famoso del mondo: Biscotto al cioccolato, mousse Lindor e ganache Lindor con granella di nocciole',
        'price' => '5.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Love Cake',
        'description' => 'Una torta dal gusto leggero per gli amanti della frutta: Biscotto al cioccolato, mousse al cioccolato bianco e yogurt, palè ai frutti di bosco e glassa di amarena',
        'price' => '5.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Oro Verde',
        'description' => 'Il nostro tributo al pistacchio, la nostra torta puù venduta: Biscotto al cioccolato, mousse al pistacchio, croccante al pistacchio e glassa al pistacchio',
        'price' => '6.00',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Waffle',
        'description' => 'Dolce a cialde, croccante fuori e morbido internamente con crema a scelta',
        'price' => '5.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Cuore Caldo Cioccolato',
        'description' => 'Cuore caldo classico, realizzato con cioccolato fondente Lindt 61%, ricoperto con lo stesso cioccolato fondente fuso',
        'price' => '4.50',
        'img' => '',
        'veg' => 1,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'name' => 'Cuore Caldo Baiocco',
        'description' => 'Un involucro alla nocciola che nasconde un cuore caldo di nutella, al suo esterno nutella e il famoso biscotto da cui prende ispirazione',
        'price' => '5.00',
        'img' => '',
        'veg' => 0,
        'availability' => 1,
	    'restaurant_id' => '9'
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca Big bang 260 g',
        'description' => "Prosciutto cotto alta qualità, mozzarella fior di latte, insalata Iceberg croccante, cipolle di Tropea Calabria IGP caramellate, pomodori ciliegino rossi semidry, pomodori ciliegino gialli semidry, salsa maionese",
        'price' => '9.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/aobzkmatmis9idtwu6jc',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca crudo 260 g',
        'description' => "Crudo di Parma 18 mesi DOP, mozzarella fior di latte",
        'price' => '8.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/ausgmpqxtld0xryfzlm8',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca cotto 260 g',
        'description' => "Prosciutto cotto alta qualità, mozzarella fior di latte, salsa maionese",
        'price' => '7.50',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/yz9ta6mdggjn1ghhdicj',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca estiva 130 g',
        'description' => "Crudo di Parma 18 mesi DOP, pomodori Pachino Confit, insalata Iceberg croccante, stracciatella pugliese",
        'price' => '7.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/ujlbjxe0trfqrcccoznx',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca montagna 130 g',
        'description' => "Speck IGP, funghi Porcini trifolati, scamorza affumicata, mozzarella fior di latte",
        'price' => '7.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/dn8efvyqjykv6rmn5lhx',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca Valtellina 260 g',
        'description' => "Bresaola punta d’anca della Valtellina IGP, rucola, bufala campana DOP, scaglie di Grana Padano 18 mesi",
        'price' => '9.50',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/qxrwlrgng77mloxhbbdh',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca italica 260 g - Edizione limitata estate 2021',
        'description' => "Tonno pinne gialle, insalata Valeriana, pomodorini rossi e gialli, mozzarella di Bufala, salsa maionese",
        'price' => '10.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/iki128qqdsdsdprwyzqh',
        'veg' => 0,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca strudel 130 g',
        'description' => "Mele, polvere di cannella, pinoli, uvetta, zucchero di canna, succo di limone",
        'price' => '6.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/aqq0uhdnwjkpbf19uydr',
        'veg' => 1,
        'availability' => 1
    ],
    [
        'restaurant_id' => '8',
        'name' => 'Spacca pistacchio 130 g',
        'description' => "Crema al pistacchio, latte condensato, granella di pistacchio",
        'price' => '6.00',
        'img' => 'https://res.cloudinary.com/glovoapp/w_600,f_auto,q_auto/Products/nu6hd7q6pkx7n7egnvzc',
        'veg' => 1,
        'availability' => 1
    ]
];

return $data;
?>