<?php 

$data = [
	[
		'name' => 'Gambero e tartufo',
		'description' => 'gambero e tartufo, 8 pezzi.',
		'price' => '13,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Involtini di primavera',
		'description' => 'Carote, cipolla e cavoli, 2 pezzi',
		'price' => '2,00',
		'img' => '',
		'veg' => 'true',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Patatine',
		'description' => 'Patatine fritte',
		'price' => '3,00',
		'img' => '',
		'veg' => 'true',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli alla griglia',
		'description' => 'Farina, carne di maiale, 4 pezzi',
		'price' => '3,50',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli di carne al vapore',
		'description' => 'Farina e carne di maiale, 4 pezzi',
		'price' => '3,50',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Ravioli di gamberi giapponesi',
		'description' => 'Farina di frumento, zenzero e gamberi, 4 pezzi',
		'price' => '4,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'false',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Sashimi sake',
		'description' => 'Filetti di salmone, 13 pezzi',
		'price' => '12,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Sashimi tuna',
		'description' => 'Filetti di tonno, 13 pezzi',
		'price' => '13,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri sake',
		'description' => 'Riso, salmone, 2 pezzi',
		'price' => '2,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri suzuki',
		'description' => 'Riso, branzino, 2 pezzi',
		'price' => '2,50',
		'img' => '',
		'veg' => 'false',
		'availability' => 'false',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri maguro',
		'description' => 'Riso, tonno, 2 pezzi',
		'price' => '3,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Nigiri ebiten',
		'description' => 'Riso, gambero fritto, 2 pezzi',
		'price' => '4,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Uramaki ebiten',
		'description' => 'tempura di gamberi, salsa teriyaki, pasta kataifi e sesamo',
		'price' => '8,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
	[
		'name' => 'Uramaki Tiger Roll',
		'description' => 'tempura di gamberi, salsa teriyaki, rivestito con salmone',
		'price' => '12,00',
		'img' => '',
		'veg' => 'false',
		'availability' => 'true',
		'restaurant_id' => '6',
	],
    [
        'name' => 'Piadina Falafel Veggie',
        'description' => 'Piadina con polpette di ceci e spezie, insalata, patatine e salsa a scelta',
        'price' => '4,50',
        'img' => '',
        'veg' => 'true',
        'availability' => 'true',
    ],
    [
        'name' => 'Beef Burger',
        'description' => 'Panino con burger di manzo, formaggio, cetrioli, pomodoro e insalata',
        'price' => '3,70',
        'img' => '',
        'veg' => 'false',
        'availability' => 'false',
    ],
    [
        'name' => 'Indiano',
        'description' => '1 samosa, 1 cingara, 1 involtino primavera',
        'price' => '5,00',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],
    [
        'name' => 'Riso Biryani',
        'description' => 'Riso biryani con carne di vitello',
        'price' => '6,00',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],
    [
        'name' => 'Kebab al Curry',
        'description' => 'Salsa al curry, pomodoro, lattuga e kebab',
        'price' => '5,00',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],
    [
        'name' => 'Kebab al pepe verde',
        'description' => 'Salsa al pepe verde, cipolla, pomodoro, lattuga e kebab',
        'price' => '4,00',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],
    [
        'name' => 'Kebab Mediterraneo',
        'description' => 'Salsa mediterranea, lattuga, pomodoro, cipolla e kebab',
        'price' => '6,20',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],
    [
        'name' => 'Piatto Hallal',
        'description' => 'Salsa al curry, salsa allo yogurt, pomodoro, lattuga, cipolla, peperoni, radicchio, kebab, patatine',
        'price' => '7,00',
        'img' => '',
        'veg' => 'false',
        'availability' => 'true',
    ],

];

return $data;
?>